### ISSUE TITLE
error migrating from 0.6.13 -> 0.7.0

### ISSUE THREAD

**Issue by mrob95** [stac-utils/pgstac#189]
Running `pypgstac migrate --debug` from a `ghcr.io/stac-utils/pgstac:v0.7.0` container gives:

```
DEBUG:pypgstac.db:PG VERSION: 13.8.
INFO:pypgstac.migrate:Migrating PGStac on PostgreSQL Version 13.8
DEBUG:pypgstac.db:VERSION: 0.6.13
INFO:pypgstac.migrate:Migrating from 0.6.13 to 0.7.0.
DEBUG:pypgstac.migrate:Running migration file pgstac.0.6.13-0.7.0.sql.
DEBUG:smart_open.smart_open_lib:{'uri': '/opt/src/pypgstac/pypgstac/migrations/pgstac.0.6.13-0.7.0.sql', 'mode': 'r', 'buffering': -1, 'encoding': None, 'errors': None, 'newline': None, 'closefd': True, 'opener': None, 'compression': 'infer_from_extension', 'transport_params': None}
INFO:pypgstac.db:NOTICE - role "pgstac_admin" already exists, skipping
INFO:pypgstac.db:NOTICE - role "pgstac_read" already exists, skipping
INFO:pypgstac.db:NOTICE - role "pgstac_ingest" already exists, skipping
INFO:pypgstac.db:NOTICE - role "user_postgres_admin" is already a member of role "pgstac_admin"
INFO:pypgstac.db:NOTICE - must be owner of table _items_15, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_18, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_6, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_3, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_13, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_14, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_26, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_25, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_27, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_30, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_5, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_7, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_8, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_12, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_22, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_19, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_21, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_24, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_28, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_29, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_17, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_10, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_32, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_23, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_20, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_33, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_34, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_9, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_4, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_31, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_11, skipping
INFO:pypgstac.db:NOTICE - must be owner of table _items_2, skipping
INFO:pypgstac.db:NOTICE - schema "pgstac" already exists, skipping
Traceback (most recent call last):
  File "/usr/local/bin/pypgstac", line 8, in <module>
    sys.exit(cli())
  File "/opt/src/pypgstac/pypgstac/pypgstac.py", line 118, in cli
    fire.Fire(PgstacCLI)
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/src/pypgstac/pypgstac/pypgstac.py", line 57, in migrate
    return migrator.run_migration(toversion=toversion)
  File "/opt/src/pypgstac/pypgstac/migrate.py", line 143, in run_migration
    cur.execute(migration_sql)
  File "/usr/local/lib/python3.9/dist-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.InsufficientPrivilege: permission denied for table _items_15
```

The migration to 0.6.13 was run on `2023-02-21T17:56:48.969Z`

Do you have any thoughts on what the issue may be?

**Comment by mrob95** [comment]
Ah, these tables are created by `partitions_trigger_func`, which doesn't exist any more. It looks like they were created with a different owner, presumably because that was the user which created the partitions.

Is there any danger in deleting or switching the owner of these tables?

**Comment by mrob95** [comment]
updated the owner to pgstac_admin manually and the migration passed
