### ISSUE TITLE
TypeError: 'row_factory' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/pgstac#195]
```python
>>> import psycopg2
>>> from pypgstac.db import PgstacDB
>>> from pypgstac.load import Loader
>>> 
>>> rds_connection = psycopg2.connect(host="*.rds.amazonaws.com", database="dummy", user="user", password="***")
>>> db_loader = Loader(db=PgstacDB(connection=rds_connection))
>>> db_loader.check_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/bitnami/python/lib/python3.11/site-packages/pypgstac/load.py", line 158, in check_version
    db_version = self.db.version
                 ^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.11/site-packages/pypgstac/db.py", line 229, in version
    version = self.query_one(
              ^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.11/site-packages/pypgstac/db.py", line 215, in query_one
    r = next(self.query(*args, **kwargs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.11/site-packages/pypgstac/db.py", line 189, in query
    with conn.cursor(row_factory=row_factory) as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'row_factory' is an invalid keyword argument for this function
```

However, when passing the DSN to PgstacDB instead of using a connection, everything works perfectly.

**Comment by drnextgis** [comment]
You are right @vincentsarago!

```python
>>> import psycopg
>>> from pypgstac.db import PgstacDB
>>> from pypgstac.load import Loader
>>> 
>>> rds_connection = psycopg.connect("host=*.rds.amazonaws.com dbname=dummy user=user password=***")
>>> db_loader = Loader(db=PgstacDB(connection=rds_connection))
>>> db_loader.check_version()
>>> db_loader.db.version
'0.7.10'
```

**Comment by vincentsarago** [comment]
can we close then ?
