### ISSUE TITLE
pyPgSTAC still uses `pipes` module despite it being deprecated in Python 3.11

### ISSUE THREAD

**Issue by GeoSpark** [stac-utils/pgstac#328]
`pipes` was deprecated in Python 3.11 and removed in 3.13 See: https://docs.python.org/3.13/library/pipes.html

**Comment by bitner** [comment]
@GeoSpark I don't believe that we are directly using that library, if it is getting installed, it must be in one of our dependencies. I'm not going to hunt that down, but I'm happy to review any PRs!

**Comment by luipir** [comment]
FYI 

18:20 $ pypgstac loads
Traceback (most recent call last):
  File "./envs/default/bin/pypgstac", line 5, in <module>
    from pypgstac.pypgstac import cli
  File "./envs/default/lib/python3.13/site-packages/pypgstac/pypgstac.py", line 7, in <module>
    import fire
  File "./envs/default/lib/python3.13/site-packages/fire/__init__.py", line 21, in <module>
    from fire.core import Fire
  File "./envs/default/lib/python3.13/site-packages/fire/core.py", line 59, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
