### ISSUE TITLE
Issues running migrations

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pgstac#7]
Working on a project that had pypgstac 0.2.3 installed

Running `pypgstac migrate` against a development database using image `bitner/pgstac:0.1.9`, I got the error:

```
root@39835833116a:/opt/src# pypgstac migrate --dsn postgresql://username:password@database:5432/postgis
Traceback (most recent call last):
  File "/opt/conda/bin/pypgstac", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/pypgstac/pypgstac.py", line 125, in migrate
    typer.echo(asyncio.run(run_migration(dsn)))
  File "/opt/conda/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.8/site-packages/pypgstac/pypgstac.py", line 110, in run_migration
    await conn.execute(migration_sql)
  File "/opt/conda/lib/python3.8/site-packages/asyncpg/connection.py", line 297, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 336, in query
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "'0.2.3'"
```

I then updated to pypgstac 0.2.4 and reran, and got the error:

```
root@62d1d24ad3c3:/opt/src# pypgstac migrate --dsn postgresql://username:password
@database:5432/postgis
Traceback (most recent call last):
  File "/opt/conda/bin/pypgstac", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/pypgstac/pypgstac.py", line 125, in migrate
    typer.echo(asyncio.run(run_migration(dsn)))
  File "/opt/conda/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.8/site-packages/pypgstac/pypgstac.py", line 110, in run_migration
    await conn.execute(migration_sql)
  File "/opt/conda/lib/python3.8/site-packages/asyncpg/connection.py", line 297, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 336, in query
asyncpg.exceptions.DuplicateObjectError: constraint "items_collections_fk" for relation "items" already exists
```

**Comment by lossyrob** [comment]
I then removed the docker volume used by the container and updated the image to `bitner/pgstac:0.2.4`. Running migrate again gave:

```
root@934e25efea4a:/opt/src# pypgstac migrate --dsn postgresql://username:password@database:5432/postgis
Traceback (most recent call last):
  File "/opt/conda/bin/pypgstac", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/pypgstac/pypgstac.py", line 125, in migrate
    typer.echo(asyncio.run(run_migration(dsn)))
  File "/opt/conda/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.8/site-packages/pypgstac/pypgstac.py", line 110, in run_migration
    await conn.execute(migration_sql)
  File "/opt/conda/lib/python3.8/site-packages/asyncpg/connection.py", line 297, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 336, in query
asyncpg.exceptions.DuplicateTableError: relation "migrations" already exists
```
