### ISSUE TITLE
Issue running migration against DB with sslmode=require

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pgstac#8]
Running migrations against a --dsn that has ?sslmode=require (or with PGSSLMODE=require), I get:

```
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f4882e35e20>
transport: <_SelectorSocketTransport closing fd=8>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "/opt/conda/lib/python3.8/asyncio/selector_events.py", line 916, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/opt/conda/lib/python3.8/asyncio/selector_events.py", line 711, in _fatal_error
    self._force_close(exc)
  File "/opt/conda/lib/python3.8/asyncio/selector_events.py", line 723, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I'm able to connect to the database using the same dsn using `psql`. Any ideas?

**Comment by lossyrob** [comment]
.. It seems that pypgstac did run the migration, but perhaps this is an error that happens on closing?

I'm not seeing any of the logging output when running `pypgstac migrate` - perhaps that should be output another way?

**Comment by bitner** [comment]
Looks like this is related to https://github.com/MagicStack/asyncpg/issues/737

**Comment by bitner** [comment]
I think this might be fixed in asyncpg 2.3 
https://github.com/MagicStack/asyncpg/pull/720

I'll try updating the asyncpg version pin.
