### ISSUE TITLE
pgstac seems to require globally unique item IDs contrary to STAC spec

### ISSUE THREAD

**Issue by robintw** [stac-utils/pgstac#84]
I've been loading some STAC items into my pgstac instance, and it seems that pgstac requires globally unique Item IDs. For example, if I create a new collection, and then add an item that I've already added, with the same ID as an existing item, then I get the following error:

```
$ pypgstac load items bec-items.json
How to deal conflicting ids (insert, insert_ignore, upsert) [insert]:
loading bec-items.json into items using insert
Traceback (most recent call last):
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\Scripts\pypgstac.exe\__main__.py", line 7, in <module>
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\pypgstac\pypgstac.py", line 43, in load
    typer.echo(asyncio.run(load_ndjson(file=file, table=table, dsn=dsn, method=method)))
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\pypgstac\load.py", line 246, in load_ndjson
    await load_iterator(f, table, conn, method)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\pypgstac\load.py", line 230, in load_iterator
    await copy(iter, table, conn)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\pypgstac\load.py", line 134, in copy
    await conn.copy_to_table(
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\asyncpg\connection.py", line 859, in copy_to_table
    return await self._copy_in(copy_stmt, source, timeout)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\anglo\lib\site-packages\asyncpg\connection.py", line 1041, in _copy_in
    return await self._protocol.copy_in(
  File "asyncpg\protocol\protocol.pyx", line 506, in copy_in
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "items_p1999w52_datetime_id_idx"
DETAIL:  Key (datetime, id)=(2000-01-01 00:00:00+00, 4096a_0_10.0_32_7_-46) already exists.
```

Is this intentional? The [STAC spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields) states that:

> The ID should be unique within the Collection that contains the Item.

**Comment by bitner** [comment]
This is correct, currently pgstac is set to that items have a globally unique id. The key word in the spec is *should* as opposed to *must*. There is some level of overhead in keeping multi-column primary keys rather than single column and the use case / catalog that PGStac was initially created for prioritized reducing that overhead.

**Comment by robintw** [comment]
Thanks - that makes perfect sense.

**Comment by duckontheweb** [comment]
> currently pgstac is set to that items have a globally unique id.

Actually, I don't think this is true. The example above shows that there is a uniqueness constraint on the combination of `datetime` and `id`. If someone inserted another Item with the same `id` but a different `datetime` then it would not violate the uniqueness constraint. This issue appears to have been raised for PgSTAC < 0.5.0; for versions of PgSTAC >= 0.5.0 the same would apply to unique combinations of `collection` and `id`. 

This does not change the original response to this post, but does have implications for stac-utils/stac-fastapi#381.
